version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-task-manager
    restart: always
    environment:
      POSTGRES_USER: miq
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: task_manager_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-manager-network

volumes:
  postgres_data:

networks:
  task-manager-network:
