jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start Docker Services
        run: docker-compose -f backend/docker-compose.yml up -d

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Wait for Database to Initialize
        run: sleep 10 # Give PostgreSQL time to start

      - name: Run Tests
        working-directory: backend
        run: mvn test
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/task_manager_db
          SPRING_DATASOURCE_USERNAME: miq
          SPRING_DATASOURCE_PASSWORD: 12345
